apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #namespace: my-app              #For if you wanted to execute this role in the namespace "my-app"
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]